apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
  namespace: genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
        - name: rag-service
          image: rag-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: genai
spec:
  selector:
    app: rag-service
  ports:
    - port: 8000
      targetPort: 8000
